language: generic
sudo: false
script: ./boot travis
branches:
  only:
    - master
before_cache:
  - rm -rf $HOME/.boot/cache/tmp/
cache:
  directories:
    - $HOME/.m2
    - $HOME/.boot
    - $HOME/boot
    - $HOME/zulu
matrix:
  include:
    - env: JDK=zulu8 UTRECHT_TEST_DB="utrecht_test"
    - env: JDK=zulu9 UTRECHT_TEST_DB="utrecht_test"
  allow_failures:
   - env: JDK=zulu9 UTRECHT_TEST_DB="utrecht_test"

services:
  - postgresql
before_script:
  - psql -c 'create database utrecht_test;' -U postgres
before_install:
  - curl -fsSLo init.sh http://irresponsible.github.io/tools.travis.jdk-installer/init.sh
  - source init.sh
  - install_jdk "${JDK}"
  - install_boot
  - setup_boot_env
  - java -version
install:
  - ./boot travis-installdeps
  - ./boot show -d
