language: clojure
sudo: false
script: ./boot travis
branches:
  only:
    - master
before_cache:
  - rm -rf $HOME/.boot/cache/tmp/
cache:
  directories:
    - $HOME/.m2
    - $HOME/.boot
    - $HOME/boot
matrix:
  include:
    - jdk: oraclejdk8
      env: BOOT_SH_VERSION=2.5.2 BOOT_VERSION=2.7.1 UTRECHT_TEST_DB="utrecht_test"
services:
  - postgresql
before_script:
  - psql -c 'create database utrecht_test;' -U postgres
install:
  - eval '[[ -f boot ]] || curl -fsSLo boot https://github.com/boot-clj/boot-bin/releases/download/${BOOT_SH_VERSION}/boot.sh'
  - chmod 755 boot
  - export BOOT_JVM_OPTIONS="-Xmx2g -client -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xverify:none -XX:+CMSClassUnloadingEnabled"
  - ./boot travis-installdeps
  - ./boot show -d
